//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using LobbySample;


namespace Assembly_CSharp.Generated
{
    [BurstCompile]
    public struct LobbySampleReadyBroadcastRpcSerializer : IComponentData, IRpcCommandSerializer<LobbySample.ReadyBroadcastRpc>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in LobbySample.ReadyBroadcastRpc data)
        {
            writer.WriteInt((int) data.playerId);
            writer.WriteUInt(data.readyState ? 1u : 0);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state,  ref LobbySample.ReadyBroadcastRpc data)
        {
            data.playerId = (int) reader.ReadInt();
            data.readyState = (reader.ReadUInt() != 0) ? true : false;
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<LobbySampleReadyBroadcastRpcSerializer, LobbySample.ReadyBroadcastRpc>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class LobbySampleReadyBroadcastRpcRpcCommandRequestSystem : RpcCommandRequestSystem<LobbySampleReadyBroadcastRpcSerializer, LobbySample.ReadyBroadcastRpc>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
