//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using LobbySample;


namespace Assembly_CSharp.Generated
{
    [BurstCompile]
    public struct LobbySampleSetupLobbyRequestSerializer : IComponentData, IRpcCommandSerializer<LobbySample.SetupLobbyRequest>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in LobbySample.SetupLobbyRequest data)
        {
            writer.WriteFixedString32(data.name);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state,  ref LobbySample.SetupLobbyRequest data)
        {
            data.name = reader.ReadFixedString32();
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<LobbySampleSetupLobbyRequestSerializer, LobbySample.SetupLobbyRequest>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class LobbySampleSetupLobbyRequestRpcCommandRequestSystem : RpcCommandRequestSystem<LobbySampleSetupLobbyRequestSerializer, LobbySample.SetupLobbyRequest>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
